global:
  scrape_interval: 15s #ποσο συχνα συλλεγονται δεδομενα

scrape_configs: #ρυθμισεις για τα endpoints που θα συλλεγουν δεδομενα
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080'] #cadvisor ειναι το container που τρεχει το cadvisor και 8080 ειναι το port που δειχνει τα metrics του
      
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100'] #node-exporter ειναι το container που τρεχει το node-exporter και 9100 ειναι το port που δειχνει τα metrics του